---
- name: Install NeoVim and set up configuration
  hosts: localhost
  connection: local
  become_user: '{{ ansible_user }}'

  tasks:
    - name: Install Dependencies
      become: yes
      become_user: root
      package:
        name:
        - gcc
        - make
        - zig
        - npm
        - go
        - unzip
        - ripgrep
        - xclip
        - neovim
        state: present

    - name: Clone NeoVim configuration repository
      git:
        repo: 'https://github.com/GL0K3/config-base'
        dest: '/home/{{ ansible_user }}/tmp/config-base'
        clone: yes
        update: yes

    - name: Ensure configuration directory exists
      file:
        path: '/home/{{ ansible_user }}/.config/'
        state: directory

    - name: Copy NeoVim configuration to the user's directory
      copy:
        src: '/home/{{ ansible_user }}/tmp/config-base/nvim'
        dest: '/home/{{ ansible_user }}/.config/'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

    - name: Ensure corrent recursive permissions set on .config
      file:
        path: '/home/{{ ansible_user }}/.config/'
        recurse: yes
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

  handlers:
    - name: Restart NeoVim
      systemd:
        name: nvim
        state: restarted

