---
- name: Install NeoVim and set up configuration
  hosts: all
  become: yes  # This will use sudo for tasks

  tasks:
    - name: Install NeoVim
      package:
        name: nvim
        state: present

    - name: Clone NeoVim configuration repository
      git:
        repo: 'https://github.com/GL0K3/config-base'
        dest: '/tmp/config-base'
        clone: yes
        update: yes

    - name: Ensure configuration directory exists
      file:
        path: '/home/{{ ansible_user }}/config/nvim'
        state: directory
        mode: '0755'

    - name: Copy NeoVim configuration to the user's directory
      copy:
        src: '/tmp/config-base/nvim'
        dest: '/home/{{ ansible_user }}/config/nvim'
        remote_src: yes
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

  handlers:
    - name: Restart NeoVim
      systemd:
        name: nvim
        state: restarted

