---
- name: Install Dependencies
  hosts: localhost
  connection: local
  become_user: '{{ ansible_user }}'

  tasks:
    - name: Install Additional Dependencies
      become: yes
      become_user: root
      package:
        name:
        - rust
        - go
        - zig
        - npm
        - poetry
        - pyenv

        - docker
        - docker-compose

        - bottom
        - lazygit
        - fzf
        - proxychains
        - k9s

        - neovim
        - tmux
        state: present
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure user is added to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

