---
- name: Install Dependencies
  hosts: localhost
  connection: local
  become_user: '{{ ansible_user }}'

  tasks:
    - name: Install Additional Dependencies
      become: yes
      become_user: root
      package:
        name:
        - rust
        - go
        - zig
        - npm
        - poetry
        - pyenv

        - bottom
        - lazygit
        - fzf
        - proxychains
        - k9s

        - neovim
        - tmux
        state: present
