---
- name: Install Proxy and set up configuration
  hosts: localhost
  connection: local
  vars_files:
    - vault/proxy.yml

  tasks:
    - name: Install Dependencies
      become_user: root
      become: yes
      package:
        name:
        - proxychains
        - rust
        state: present

    - name: Install cargo package sslocal
      command: cargo install shadowsocks-rust

    - name: Copy proxychains config
      copy:
        src: files/proxychains.conf
        dest: /etc/proxychains.conf

    - name: Create config file for proxy service
      template:
        src: ssconfig.json
        dest: /etc/ssconfig.json

    - name: Add service file to services 1
      become: yes
      become_user: root
      template:
        src: sslocal.service
        dest: /etc/systemd/system/sslocal.service
        owner: root
        group: root
        mode: '0644'

    - name: Add service file to services 2
      become: yes
      become_user: root
      template:
        src: sslocal.service
        dest: /lib/systemd/system/sslocal.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload Daemon
      systemd:
        daemon_reload: yes

    - name: Append alias to run several commands using proxy
      lineinfile:
        path: '/home/{{ ansible_user }}/.bashrc'
        line: |
          alias proxy="proxychains -q"
          alias v="proxy nvim"
        create: yes

    - name: Start the service
      service:
        name: sslocal
        state: started
        enabled: yes
      ignore_errors: yes
