---
- name: Install Tmux and set up configuration
  hosts: localhost
  connection: local
  become_user: '{{ ansible_user }}'

  tasks:
    - name: Install kubectl
      become: yes
      become_user: root
      package:
        name: kubectl
        state: present

    - name: Copy kubernetes config
      copy:
        src: config
        dest: '/home/{{ ansible_user }}/.kube/config'
