---
- name: Install Tmux and set up configuration
  hosts: localhost
  connection: local
  become_user: '{{ ansible_user }}'
  vars_files:
    - vault/kube_config.yml


  tasks:
    - name: Install kubectl
      become: yes
      become_user: root
      package:
        name: kubectl
        state: present

    - name: Copy kubernetes config
      copy:
        content: "{{ kube_config }}"
        dest: '/home/{{ ansible_user }}/.kube/config'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0644
