---
- name: Install Tmux and set up configuration
  hosts: localhost
  connection: local
  become_user: '{{ ansible_user }}'

  tasks:
    - name: Install Dependencies and Tmux
      become: yes
      become_user: root
      package:
        name:
        - xclip
        - fzf
        - bottom
        - tmux
        state: present

    - name: Ensure configuration directory exists
      file:
        path: '/home/{{ ansible_user }}/.tmux/'
        state: directory

    - name: Check if TPM is already installed
      stat:
        path: "/home/{{ ansible_user }}/.tmux/plugins/tpm"
      register: tpm_dir

    - name: Install Tmux Plugin Manager if needed
      git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: '/home/{{ ansible_user }}/.tmux/plugins/tpm'
        clone: yes
        update: yes
      when: not tpm_dir.stat.exists

    - name: Clone Tmux configuration repository
      git:
        repo: 'https://github.com/GL0K3/config-base'
        dest: '/home/{{ ansible_user }}/tmp/config-base'
        clone: yes
        update: yes

    - name: Copy Tmux configuration content
      copy:
        src: '/home/{{ ansible_user }}/tmp/config-base/tmux/tmux/'
        dest: '/home/{{ ansible_user }}/.tmux/'
        remote_src: yes
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

    - name: Create symlink for .tmux.conf
      file:
        src: '/home/{{ ansible_user }}/.tmux/tmux.conf'
        dest: '/home/{{ ansible_user }}/.tmux.conf'
        state: link
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        force: yes

    - name: Ensure corrent recursive permissions set on .tmux
      file:
        path: '/home/{{ ansible_user }}/.tmux/'
        recurse: yes
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

    - name: Add custom g.sh script as executable
      copy:
        src: '/home/{{ ansible_user }}/tmp/config-base/tmux/g.sh'
        dest: '/home/{{ ansible_user }}/.g.sh'
        remote_src: yes
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0755'

    - name: Append alias to run g.sh as g command
      lineinfile:
        path: '/home/{{ ansible_user }}/.bashrc'
        line: 'alias g=". /home/{{ ansible_user }}/.g.sh"'
        create: yes

    - name: Create Project folder in user dirrectory for g.sh
      file:
        path: '/home/{{ ansible_user }}/Projects'
        state: directory
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

    - name: Download plugins
      become_user: '{{ ansible_user }}'
      command: |
        /home/{{ ansible_user }}/.tmux/plugins/tpm/bin/install_plugins

    - name: Remove tmux-1000
      become: yes
      become_user: root
      file:
        path: '/tmp/tmux-1000/'
        state: absent
