---
- name: Install Tmux and set up configuration
  hosts: localhost
  connection: local
  become_user: '{{ ansible_user }}'

  tasks:
    - name: Install oh-my-bash
      command: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

    - name: Append alias to run g.sh as g command
      lineinfile:
        path: '/home/{{ ansible_user }}/.bashrc'
        line: |
          alias copy='xclip -selection clipboard'
          alias paste='xclip -selection clipboard -o'
        create: yes

    - name: Add custom s.sh script as executable
      copy:
        src: '/home/{{ ansible_user }}/tmp/config-base/bash/s.sh'
        dest: '/home/{{ ansible_user }}/.s.sh'
        remote_src: yes
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0755'

    - name: Append alias to run s.sh as s command
      lineinfile:
        path: '/home/{{ ansible_user }}/.bashrc'
        line: 'alias s="~/.s.sh"'
        create: yes
